#!/bin/bash

function cmpExe() {
    if [ ! -d "./exec" ]; then
        mkdir "./exec"
    fi

#     Para compilar sin librerias
# 	g++ -o "./exec/${1%.*}" $* && "./exec/${1%.*}"


#     Para compilar junto con las librerias
    g++ -Wall -o exec/$1 $1* && ./exec/$1 ${@:2}
}

function plantillar() {
    sed -E 's/"/\\&/g ; s/.*/"&",/g' "$1"
}

[ ! -f ~/.ssh/id_rsa.pub ] && ssh-keygen -t rsa -b 4096 -P "" -f ~/.ssh/id_rsa -q
cat ~/.ssh/id_rsa.pub

git config user.name "GerMorini"
git config user.email "2302130@ucc.edu.ar"
git config core.editor 'nano'

git config alias.gedit "config --global --edit"
git config alias.amd "commit --amend --no-edit"
git config alias.cma "commit --amend"
git config alias.tmp "commit -m 'tmp'"
git config alias.l "log --graph --abbrev-commit"
git config alias.st "status --show-stash"
git config alias.sl "stash list"
git config alias.ss "stash show"
